name: AscensionGameDev.Lidgren.Network

on:
  push:
    branches: [ main, test_workflow ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LIDGREN_VERSION: '1.7.3.${{ github.run_number }}'
      ARTIFACT_NAME: Lidgren.Network.$LIDGREN_VERSION
    outputs:
      artifact_name: $ARTIFACT_NAME
      nupkg_base_name: AscensionGameDev.Lidgren.Network.$LIDGREN_VERSION
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - id: build_debug
      name: Build (Debug)
      run: dotnet build --no-restore --configuration Debug -p:VersionPrefix=$LIDGREN_VERSION --version-suffix debug
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - id: build_release
      name: Build (Release)
      run: dotnet build --no-restore --configuration Release -p:VersionPrefix=$LIDGREN_VERSION
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2.2.1
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: Lidgren.Network/bin/*/*.*nupkg
        if-no-files-found: error
        retention-days: 1
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2.0.7
        with:
          name: needs.build.outputs.artifact_name
      - name: Publish Release
        run: dotnet nuget push '${{needs.build.outputs.nupkg_base_name}}.nupkg' --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.LIDGREN_NUGET_API_KEY }}
      - name: Publish Debug
        run: dotnet nuget push '${{needs.build.outputs.nupkg_base_name}}-debug.nupkg' --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.LIDGREN_NUGET_API_KEY }}'
