name: AscensionGameDev.Lidgren.Network

on:
  push:
    branches: [ main, test_workflow ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - id: build_debug
      name: Build (Debug)
      run: dotnet build --no-restore --configuration Debug -p:VersionPrefix='1.7.3.${{ github.run_number }}' --version-suffix debug
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - id: build_release
      name: Build (Release)
      run: dotnet build --no-restore --configuration Release -p:VersionPrefix='1.7.3.${{ github.run_number }}' 
    - run: echo "${{ toJSON(steps.build_debug.outputs) }}"
    - run: echo "${{ toJSON(steps.build_release.outputs) }}"
#   publish:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Publish Release
#         run: dotnet nuget push "bin/Release/*.nupkg" -k ${{ secrets.LIDGREN_NUGET_API_KEY }}
#       - name: Publish Debug
#         run: dotnet nuget push "bin/Debug/*.nupkg" -k ${{ secrets.LIDGREN_NUGET_API_KEY }}'
