name: AscensionGameDev.Lidgren.Network

on:
  push:
    branches: [ main, test_workflow ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build (Debug)
      run: dotnet build --no-restore --configuration Debug
    - name: Build (Release)
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Dump version
        run: echo '1.7.${{ GITHUB_RUN_ID }}'
      - name: Dump fake secret
        run: echo ${{ secrets.FAKE_SECRET }}
      - name: Dump GITHUB_RUN_NUMBER
        run: echo ${{ GITHUB_RUN_NUMBER }}
      - name: Dump workflow name
        run: echo ${{ GITHUB_WORKFLOW }}
#       - name: Publish NuGet.org
#         uses: brandedoutcast/publish-nuget@v2.5.5
#         with:
#           PROJECT_FILE_PATH: ./Lidgren.Network/Lidgren.Network.csproj
#           NUGET_KEY: ${{ secrets.LIDGREN_NUGET_API_KEY }}
#           VERSION_STATIC: '1.7.${GITHUB_RUN_ID}'
