name: Lidgren.Network PRs

on: pull_request

jobs:
  build_pr:
    runs-on: ubuntu-latest
    env:
      LIDGREN_VERSION: '1.8.0.${{ github.run_number }}'
      ARTIFACT_NAME: 'Lidgren.Network.1.8.0.${{ github.run_number }}'
    outputs:
      artifact_name: '${{ env.ARTIFACT_NAME }}'
      nupkg_base_name: 'AscensionGameDev.Lidgren.Network.${{ env.LIDGREN_VERSION }}'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - id: build_debug
      name: Build (Debug)
      run: dotnet build --no-restore --configuration Debug -p:VersionPrefix=$LIDGREN_VERSION --version-suffix debug
    - id: build_release
      name: Build (Release)
      run: dotnet build --no-restore --configuration Release -p:VersionPrefix=$LIDGREN_VERSION
    - name: Upload build artifacts for debugging if build failed
      uses: actions/upload-artifact@v2.2.1
      if: ${{ failure() }}
      with:
        name: '${{ env.ARTIFACT_NAME }}'
        path: Lidgren.Network/bin/*
        if-no-files-found: error
        retention-days: 1
  test_pr:
    runs-on: ubuntu-latest
    needs: build_pr
    steps:
    - uses: actions/checkout@v2
    - name: Tests (Pull Requests)
      run: dotnet test --verbosity normal
